# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Parse-AccessLogEntry-Accessor
version:      0.01
version_from: lib/Parse/AccessLogEntry/Accessor.pm
installdirs:  site
requires:
    Class::Accessor::Fast:         0
    Parse::AccessLogEntry:         0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
